// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArticleStatus } from "./ArticleStatus";

export type Article = { id: bigint, ticket_key?: string, title: string, problem: string, solution: string, expected_result?: string, prerequisites?: string, additional_notes?: string, tags: Array<string>, content_markdown: string, status: ArticleStatus, confluence_page_id?: string, confluence_url?: string, confluence_space_key?: string, quality_score?: number, template_id?: string, created_at: string, updated_at: string, };
