// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JiraComment } from "./JiraComment";

export type JiraTicket = { key: string, summary: string, description?: string, status: string, priority?: string, resolution?: string, labels: Array<string>, components: Array<string>, comments: Array<JiraComment>, created: string, updated: string, };
