// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QualityScore = { overall: number, has_title: boolean, has_problem: boolean, has_solution: boolean, has_expected_result: boolean, has_prerequisites: boolean, solution_step_count: number, word_count: number, warnings: Array<string>, };
