// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Template = { id: string, name: string, slug: string, description: string, system_prompt: string, output_structure: string, is_builtin: boolean, created_at: string, };
