// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FlaggedSection = { pattern_type: string, severity: string, matched_text: string, line_number: number, start_col: number, end_col: number, };
